// @ts-ignore .open-next/worker.js is generated by the OpenNext build.
import nextWorker from "../../.open-next/worker.js";
// @ts-ignore Cloudflare Workers provides the cloudflare:node runtime module.
import { httpServerHandler } from "cloudflare:node";
import app from "./app";

app.listen(3000);
const apiHandler = httpServerHandler({ port: 3000 });

const RUNTIME_ENV_KEYS = [
  "SUPABASE_URL",
  "SUPABASE_SERVICE_ROLE_KEY",
  "SUPABASE_ANON_KEY",
  "SUPABASE_KEY",
  "SESSION_SECRET",
  "YUNIKO_APP_URL",
  "YUNIKO_API_URL",
] as const;

export default {
  async fetch(request: Request, env: unknown, ctx: any) {
    const runtimeEnv = env as Record<string, unknown>;
    for (const key of RUNTIME_ENV_KEYS) {
      const value = runtimeEnv[key];
      if (typeof value === "string" && value.length > 0) {
        process.env[key] = value;
      }
    }

    const pathname = new URL(request.url).pathname;
    if (pathname === "/api" || pathname.startsWith("/api/")) {
      return apiHandler.fetch(request, env, ctx);
    }
    return nextWorker.fetch(request, env, ctx);
  },
};
