// @ts-ignore .open-next/worker.js is generated by the OpenNext build.
import nextWorker from "../../.open-next/worker.js";
import { handleAsNodeRequest } from "cloudflare:node";
import app from "./app";

app.listen(3000);

export default {
  async fetch(request: Request, env: unknown, ctx: ExecutionContext) {
    const pathname = new URL(request.url).pathname;
    if (pathname === "/api" || pathname.startsWith("/api/")) {
      return handleAsNodeRequest(3000, request);
    }
    return nextWorker.fetch(request, env, ctx);
  },
};
